# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0003_auto_20160202_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('file_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='file_id')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration')),
                ('performer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Performer')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='MIME type')),
                ('file_size', models.IntegerField(blank=True, default=0, null=True, verbose_name='File size')),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audios',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone number')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('user_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='telegrambot.User', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('file_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='file_id')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='File name')),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='MIME type')),
                ('file_size', models.IntegerField(blank=True, default=0, null=True, verbose_name='File size')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='PhotoSize',
            fields=[
                ('file_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='file_id')),
                ('width', models.IntegerField(default=0, verbose_name='Width')),
                ('height', models.IntegerField(default=0, verbose_name='Height')),
                ('file_size', models.IntegerField(blank=True, default=0, null=True, verbose_name='File size')),
            ],
            options={
                'verbose_name': 'PhotoSize object',
                'verbose_name_plural': 'PhotoSize objects',
            },
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('file_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='file_id')),
                ('width', models.IntegerField(default=0, verbose_name='Width')),
                ('height', models.IntegerField(default=0, verbose_name='Height')),
                ('emoji', models.CharField(blank=True, max_length=255, null=True, verbose_name='Emoji')),
                ('file_size', models.IntegerField(blank=True, default=0, null=True, verbose_name='File size')),
                ('thumb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegrambot.PhotoSize', verbose_name='Thumbnail')),
            ],
            options={
                'verbose_name': 'Sticker',
                'verbose_name_plural': 'Stickers',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('foursquare_id', models.CharField(max_length=255, verbose_name='Foursquare identifier')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegrambot.Location')),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('file_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='file_id')),
                ('width', models.IntegerField(default=0, verbose_name='Width')),
                ('height', models.IntegerField(default=0, verbose_name='Height')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration')),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='MIME type')),
                ('file_size', models.IntegerField(blank=True, default=0, null=True, verbose_name='File size')),
                ('thumb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegrambot.PhotoSize', verbose_name='Thumbnail')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('file_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='file_id')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration')),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='MIME type')),
                ('file_size', models.IntegerField(blank=True, default=0, null=True, verbose_name='File size')),
            ],
            options={
                'verbose_name': 'Voice',
                'verbose_name_plural': 'Voices',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='document',
            name='thumb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegrambot.PhotoSize', verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegrambot.Audio', verbose_name='Audio'),
        ),
        migrations.AddField(
            model_name='message',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegrambot.Contact', verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='message',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegrambot.Document', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='message',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegrambot.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ManyToManyField(blank=True, to='telegrambot.PhotoSize', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='message',
            name='sticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegrambot.Sticker', verbose_name='Sticker'),
        ),
        migrations.AddField(
            model_name='message',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegrambot.Venue', verbose_name='Venue'),
        ),
        migrations.AddField(
            model_name='message',
            name='vidoe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegrambot.Video', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='message',
            name='voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegrambot.Voice', verbose_name='Voice'),
        ),
    ]
