# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0004_auto_20160617_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='vidoe',
            new_name='video',
        ),
    ]
