# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0005_auto_20160619_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tg User ID'),
        ),
    ]
